version: '3'
services:

  icat:
    image: postgres:10
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_PASSWORD=pg_password

  irods-provider:
    environment:
      - PYTHON_RULE_ENGINE_INSTALLED=${python_rule_engine_installed}
    hostname: irods-provider
    build:
      context: docker_build
      dockerfile: Dockerfile.provider
      args:
        server_py: "${server_python_version}"
    volumes:
      - "${irods_pkg_dir}:/irods_packages:ro"
      - ./irods_shared:/irods_shared:rw
    depends_on:
      - icat
    networks:
      default:
        aliases:
          - irods-provider

  client-runner:
    env_file: client-runner.env
    environment:
      - PYTHON_RULE_ENGINE_INSTALLED=${python_rule_engine_installed}
    volumes:
      - ./irods_shared:/irods_shared:rw
    build:
      context: .
      dockerfile: Dockerfile.prc_test.${client_os_generic}
      args:
        os_image: "$client_os_image"
        py_N: "$client_python_version"
    depends_on:
      - irods-provider
